[package]
name = "certified-assets"
description = "A library for certifying assets served via HTTP, ensuring the security of query calls on the IC."
repository = "https://github.com/NatLabs/certified-assets"
version = "0.4.0"
license = "MIT"
keywords = ["assets", "http", "certification"]

[dependencies]
base = "0.13.5"
ic-certification = "0.1.3"
sha2 = "0.1.0"
http-parser = "0.3.4"
http-types = "1.0.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1@2711d18727e954b11afc0d37945608512b5fbce2"
serde = "3.1.0"
map = "9.0.1"
vector = "0.4.1"

[dev-dependencies]
test = "2.0.0"
bench = "1.0.0"
fuzz = "0.2.1"
itertools = "0.2.2"

[toolchain]
wasmtime = "24.0.0"
moc = "0.13.2"
